---
#       Supported steps:
#         sonarqube -
#         jmeter -
#         maven - 
#         pytest -
#
#       Deployment steps (supported):
#         ansible - 
config:
   app_name: 'django_todo'
   sonarqube:
      token: "sonar"
      url: "http://sonarcube:9000"
      projectKey: "toDo"
      jenkins_sonar_tool_client: 'sonar-scanner'
      jenkins_sonar_tool_server: 'sonar-scanner'
      credentialsId: 'sonar' 
   ansible:
      host: "172.17.0.5"
      env: "PROD"
      tests: false
      credentialsId: 
   jmeter:
      jmeter_install_base: "/var/jenkins_home/apache-jmeter-5.6.3"
      jmeter_bin_path: "bin/jmeter"
      test_file: "basic_test.jmx"
      input_format: "xml"
      output_format:
      output_filename:
      jmeter_addtl_args: 
   nexus:
      nexus_user: 'deploy'
      nexus_pass: 'deploy'
      nexus_server: 'http://nexus3:8081'
      nexus_server_apps: 'apps'
      credentialId: 
