---
#       Supported steps:
#         sonarqube -
#         jmeter -
#         maven - 
#         pytest -
#
#       Deployment steps (supported):
#         ansible - 
config:
   app_name: 'django_todo'
   sonarqube:
      token: "sonar"
      url: "test"
      projectKey: "test"
      credentialsId: 
   ansible:
      host: "aap.prod.hsbc"
      env: "PROD"
      tests: false
      credentialsId: 
   jmeter:
      jmeter_install_base: "/var/jenkins_home/apache-jmeter-5.6.3"
      jmeter_bin_path: "bin/jmeter"
      test_file: "basic_steps.xml"
      input_format: "xml"
      output_format:
      output_filename:
      jmeter_addtl_args: 
   nexus:
      nexus_user: 'deploy'
      nexus_pass: 'deploy'
      nexus_server: 'http://172.17.0.2:8081'
      nexus_server_apps: 'apps'
      credentialId: 
