---
- hosts: all
  vars:
    app_name: 'django_todo'
    version: '1.0'
    nexus_repo_name: 'nexus3:8081'
    nexus_user: 'deploy'
    nexus_pass: 'deploy'
    url_mode: 'http'
  tasks:
    - name: install python-setuptools by yum
      yum:
         name: "{{item}}"
         state: present
         update_cache: yes
      with_items:
         - "python-setuptools"
#         - "python-virtualenv"

    - name: Create directory app on opt
      file:
         path: "{{item}}"
         state: "directory"
         recurse: "yes"
      with_items:
         - "/opt/app/release/{{version}}"
         - "/opt/app/release"
         - "/opt/app/backup"
         
    - name: Get app from nexus
      get_url:
         url: "{{url_mode}}://{{nexus_repo_name}}/repository/apps/{{app_name}}/{{app_name}}-{{version}}.tar"
         dest: "/opt/app/backup"
         url_username: "{{nexus_user}}"
         url_password: "{{nexus_pass}}"

    - name: unarchive app dump
      unarchive:
         src: "/opt/app/backup/{{app_name}}-{{version}}.tar"
         dest: "/opt/app/release/{{version}}"
         remote_src: yes

    - name: install python requirement
      pip: 
         chdir: "/opt/app/release/{{version}}"
         requirements: "/opt/app/release/{{version}}/requirements.txt"
         virtualenv: "/opt/app/.demo"
         virtualenv_site_packages: yes

    - name: Create directory app on opt
      file:
         src: "/opt/app/release/{{version}}"
         path: "/opt/app/current"
         state: "link"
      
    - name: Run Migrations
      shell: 
        cmd: "/opt/app/.demo/bin/python manage.py migrate"
        chdir: "/opt/app/current"

    - name: Start Application
      shell: 
        cmd: "bash run_server.sh"
        chdir: "/opt/app/current"
